//Primary
var WHITE = "#E3EAF7";
var BLACK = "#1B2934";
var GRAY = "#C5CBD6";
var ACCENT1 = "#261435";
var ACCENT2 = "#414770";
var ACCENT3 = "#5B85AA";
//Elements
var TEXT = BLACK;
var PAGE = WHITE;
var BORDER = GRAY;
var TOOLBAR = ACCENT1;
var TOOLBAR_TEXT = WHITE;
var LIST_ITEM_TITLE = ACCENT2;
var LIST_ITEM_TEXT = TEXT;
var LIST_ITEM_SUBTEXT = ACCENT2;
var LIST_ITEM_HEAD = ACCENT3;
var LIST_ITEM_HIGHLIGHT = ACCENT3;
