//Primary
var BLANK = "#FFF";
var WHITE = "#E3EAF7";
var BLACK = "#1B2934";
var LIGHT = Qt.lighter("#40E3EAF7")
var DARK = Qt.darker("#401B2934")
var TRANSPARENT = Qt.rgba(0,0,0,0);
var GRAY = "#C5CBD6";
var ACCENT1 = "#261435";
var ACCENT2 = "#414770";
var ACCENT3 = "#5B85AA";
//Elements
var TEXT = BLACK;
var PAGE = WHITE;
var MODAL = BLANK;
var BORDER = GRAY;
var TOOLBAR = TRANSPARENT;
var TOOLBAR_TEXT = WHITE;
var LIST_ITEM_TITLE = ACCENT3;
var LIST_ITEM_TEXT = TEXT;
var LIST_ITEM_SUBTEXT = ACCENT2;
var LIST_ITEM_HEAD = ACCENT3;
var LIST_ITEM_HIGHLIGHT = ACCENT3;
var BUTTON = TRANSPARENT;
var BUTTON_BORDER = BORDER;
var BUTTON_TEXT = ACCENT2;
