//Typography
var FONT_SIZE = 16;//U.px(12);
var FONT_SIZE_BODY = FONT_SIZE;
var FONT_SIZE_SMALL = FONT_SIZE_BODY * 0.6;
var FONT_SIZE_SUBHEAD = FONT_SIZE_BODY * 1.4;
var FONT_SIZE_HEADLINE = FONT_SIZE_BODY * 1.6;
var FONT_SIZE_DISPLAY = FONT_SIZE_BODY * 2;
var FONT_LINE_HEIGHT = 1.2;
var FONT_LINE_HEIGHT_BODY = FONT_LINE_HEIGHT;
var FONT_LINE_HEIGHT_SUBHEAD = FONT_LINE_HEIGHT;
var FONT_LINE_HEIGHT_HEADLINE = FONT_LINE_HEIGHT * 1.25;
var FONT_LINE_HEIGHT_DISPLAY = FONT_LINE_HEIGHT_HEADLINE;
var FONT_MARGIN = FONT_SIZE_BODY * 2;
var FONT_MARGIN_BODY = FONT_MARGIN;
var FONT_MARGIN_SUBHEAD = FONT_MARGIN;
var FONT_MARGIN_HEADLINE = FONT_MARGIN * 1.25;
var FONT_MARGIN_DISPLAY = FONT_MARGIN_HEADLINE;
//Spacing
var MARGIN = 16//U.px(16);
var MARGIN_DOUBLE = MARGIN * 2;
var BORDER = 1//U.px(1);
var BORDER_DOUBLE = BORDER * 2;
//Icons
var ICON = 24//U.px(24);
var ICON_32 = 32//U.px(32);
var ICON_64 = ICON_32 * 2;
//Toolbar
var TOOLBAR = 64//U.px(64);
var TOOLBAR_MIN = TOOLBAR;
var TOOLBAR_MAX = TOOLBAR * 2;
//Lists
var LIST_ITEM = 72//U.px(72);
var LIST_TITLE = LIST_ITEM;
var LIST_ITEM_TALL = LIST_ITEM * 1.5;
var LIST_ITEM_HEAD = 48//U.px(48);
//Button
var BUTTON_RADIUS = MARGIN / 2;
